# -*- mode: ruby -*-
# vi: set ft=ruby :

iprange = "192.168.1"
domain = "shibusa.io"

Vagrant.require_version ">= 1.9.7"
Vagrant.configure("2") do |config|
  # Vagrant ssh private key
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Docker Manager Nodes
  managercount = 3
  manageripstart = 10
  (0..managercount - 1).each do |i|
    config.vm.define "managernode-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "managernode-#{i}.#{domain}"
      node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "#{iprange}.#{manageripstart + i}"
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      node.vm.provision "file", source: "./vagrantdata/VBoxGuestAdditions_5.1.26.iso", destination: "/tmp/VBoxGuestAdditions_5.1.26.iso"
      node.vm.provision :shell, path: "./vagrantdata/init.sh"
      node.vm.provision :shell, path: "./vagrantdata/vboxguest.sh"
      node.vm.provision :shell, path: "./vagrantdata/docker.sh"
      node.vm.provision :shell, path: "./vagrantdata/daemon.sh"
    end
  end

  # Docker Worker Nodes
  workercount = 3
  workeripstart = 20
  (0..workercount - 1).each do |i|
    config.vm.define "workernode-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "workernode-#{i}.#{domain}"
      node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "#{iprange}.#{workeripstart + i}"
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      node.vm.provision "file", source: "./vagrantdata/VBoxGuestAdditions_5.1.26.iso", destination: "/tmp/VBoxGuestAdditions_5.1.26.iso"
      node.vm.provision :shell, path: "./vagrantdata/init.sh"
      node.vm.provision :shell, path: "./vagrantdata/vboxguest.sh"
      node.vm.provision :shell, path: "./vagrantdata/docker.sh"
      node.vm.provision :shell, path: "./vagrantdata/daemon.sh"
    end
  end

  # Docker Registry Nodes
  registrycount = 1
  registryipstart = 30
  (0..registrycount - 1).each do |i|
    config.vm.define "registrynode-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "registrynode-#{i}.#{domain}"
      node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "#{iprange}.#{registryipstart + i}"
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      node.vm.provision "file", source: "./vagrantdata/VBoxGuestAdditions_5.1.26.iso", destination: "/tmp/VBoxGuestAdditions_5.1.26.iso"
      node.vm.provision :shell, path: "./vagrantdata/init.sh"
      node.vm.provision :shell, path: "./vagrantdata/vboxguest.sh"
      node.vm.provision :shell, path: "./vagrantdata/docker.sh"
      node.vm.provision :shell, inline: "docker run -d -p 5000:5000 --restart=always --name registry registry:2"
    end
  end
end
